### ISSUE TITLE
NPE in ComposeFormFragment

### ISSUE THREAD

**Issue by btmura** [btmura/rbb#289]
java.lang.NullPointerException
at com.btmura.android.reddit.app.ComposeFormFragment$SubmitTask.showCaptcha(ComposeFormFragment.java:725)
at com.btmura.android.reddit.app.ComposeFormFragment$SubmitTask.onPostExecute(ComposeFormFragment.java:713)
at com.btmura.android.reddit.app.ComposeFormFragment$SubmitTask.onPostExecute(ComposeFormFragment.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:631)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5118)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
at dalvik.system.NativeStart.main(Native Method)

**Comment by btmura** [comment]
I should of wrote down more context when I saw this. Right now, this points to code that adds a fragment so...
